load("@io_bazel_rules_go//go:def.bzl", "go_prefix", "go_binary", "go_library", "go_test")

go_binary(
    name = "demo",
    srcs = ["demo.go"],
    deps = [
        "//flow",
        "//packet",
    ],
)
